source 'https://rubygems.org'

gem 'opal',         :github => 'opal/opal', :tag => "v0.10.3"
gem 'opal-browser', :github => 'opal/opal-browser'
gem 'sass'
gem 'maquette',     :path => '/home/bebac/Projects/opal-maquette'
gem 'grand_central'

gem 'therubyracer'
gem 'uglifier'

group :development do
  gem 'guard'
  gem 'guard-rake'
end
